# Generated by Django 3.0.4 on 2020-04-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200403_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
    ]
