# Generated by Django 3.0.4 on 2020-04-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200405_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='people',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
