# Generated by Django 3.0.4 on 2020-04-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200405_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='people',
            field=models.TextField(blank=True, null=True),
        ),
    ]
