# Generated by Django 3.0.4 on 2020-05-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200505_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_post_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Post'),
        ),
    ]
